### ISSUE TITLE
Request: Button/link to go to latest signal

### ISSUE THREAD

**Issue by NervosaX** [christianalfoni/cerebral-chrome-extension#10]
When in historical state, if you try to fire any new signals you will receive the error:

```
Cerebral - Looking in the past, ignored signal yourSignal
```

Which makes total sense. However, if you wish to continue, the only way to do so is to mash the forward button (or reset the state entirely). This can be quite tedious, so I propose a new button or link in the debugger that goes back to the latest signal.

**Comment by christianalfoni** [comment]
Makes perfect sense :-) will bring on next version!

**Comment by christianalfoni** [comment]
Okay, in now, will be part of next release
