### ISSUE TITLE
Access to model in debugger?

### ISSUE THREAD

**Issue by delaneyj** [christianalfoni/cerebral-chrome-extension#14]
Currently if you click **model** the model does print to the console as expected however I want to ability to have one or more of the following options.
1.  When using baobab/immutable convert the output to a format that's easier to parse ( like a `console.log('CEREBRAL - model:', controller.get().toJS());` in cerebral-immutable case).
2.  Have the ability to query from the console.  With [React's chrome extension](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi) when you select a Component in the upper right there is a note saying _($r in the console)_ and this variable gives access directly to model.

Since most immutable libraries have to wrap vanilla maps & arrays it would be more helpful to have better access to this information, especially with stepping back through signals.

**Comment by christianalfoni** [comment]
Hi there,

Very good input here. It requires to update a few packages, but I think we should do that. I will let you know when I get to it :-)

**Comment by delaneyj** [comment]
Thanks @christianalfoni, cerebral is a great full framework compared to most fluxish setups!

**Comment by christianalfoni** [comment]
This should work now I believe :)
