### ISSUE TITLE
Multiple cerebral apps share signal messages

### ISSUE THREAD

**Issue by NervosaX** [christianalfoni/cerebral-chrome-extension#16]
(Maybe) related to that previous fix I made for only getting model once, etc, there's another bug where cerebral panels are shared when receiving signals.

**To replicate:**

http://www.cerebraljs.com/todomvc/#/ Open this in two windows, both debuggers open. Cause some signals to fire. You will note that both windows receive the signal. I also tested this with todomvc open and my own app, and my app was getting signals it didn't even have registered.

**Comment by christianalfoni** [comment]
Now the debugger reacts to changing app :)
