### ISSUE TITLE
Debug baobab facets

### ISSUE THREAD

**Issue by saulshanabrook** [christianalfoni/cerebral-chrome-extension#2]
I noticed that when I click `model`, the facet output is missing there. This makes sense to some degree, but when I have a bunch of facets that all call each other, it can be hard to debug, without knowing what they are all at.

Would it be possible to have some way of accessing the entire tree, with computed facet values?

**Comment by christianalfoni** [comment]
The tree is now available on `model.tree`. But facets are so specific to Baobab that it would be impossible to create something in the debugger that works for all model packages :-/

**Comment by saulshanabrook** [comment]
Yeah makes sense. That works great.
