### ISSUE TITLE
High Frequency Updates

### ISSUE THREAD

**Issue by saulshanabrook** [christianalfoni/cerebral-chrome-extension#4]
I noticed that if I have a signal triggered every 50ms or so, the debugger can't keep up. The app still functions correctly, but the debugger doesn't show the right current signal. If I change it to trigger every 100ms instead, the debugger works great.

**Comment by christianalfoni** [comment]
Yeah, I can put a debounce on that, good idea :-)

It is really tricky to communicate with chrome extensions, so there is some information overload there. Adding it to cerebral next release, https://github.com/christianalfoni/cerebral/issues/99

**Comment by saulshanabrook** [comment]
:+1:
