### ISSUE TITLE
Checkboxes

### ISSUE THREAD

**Issue by christianalfoni** [christianalfoni/cerebral-chrome-extension#7]
Okay, I think we have to make the debugger simpler. This is how it works under the hood.

The application will always start in its initial state. Tracked signals can be stored in localStorage when application refreshes. When application loads again it starts from initial state and signals are loaded from localStorage. If router is present the signals will be remembered before the initial route is triggered. When debugger loads it will also remember loaded signals, in case router was not present.

I think it is a mistake to allow turning of tracking signals on and off, it should always be on. Lets say you add two items to a list, then turn off "track signals". Then you add a last item. You refresh, but will only see the last item now, because the previous signals has been discarded. I think this is confusing.

I suggest we try to let the debugger always track signals and only display a "reset state on refresh" checkbox. I also suggest to introduce two buttons next to the slider, allowing you to step back/forth instead of sliding. Or maybe just remove slider? Just have buttons for stepping? Slider is cool, but is it practical?

So the default behaviour would be that signals are always tracked, but you can choose to automatically reset the state when application resets. This is how it will work:
1. Application refreshes
2. If "reset state on refresh" was checked an empty array of signals is stored in localStorage as the app unloaded. If it was unchecked all tracked signals would be stored into localStorage ensuring that what you see in the UI is actually what will be reproduced
3. Router triggers and remembers any loaded signals
4. Router triggers initial signal
5. Debugger initializes and remembers any loaded signals, if not already remembered by router

**Comment by christianalfoni** [comment]
Okay, so I did some work on this and this is how it looks:

![screen shot 2015-09-24 at 08 13 58](https://cloud.githubusercontent.com/assets/3956929/10066552/4fd694b2-6294-11e5-8f4a-a434a835ba99.png)

So on a refresh here it will still be 2 signals and the state is reproduced. As I continue running signals they will be accumulated. If I manually hit "reset" it will of course reset. Or if I check the checkbox it will reset automatically when I refresh the page, always starting from 0 signals. A route trigger could occur of course and you would always start from 1 signal.

**Comment by Guria** [comment]
@christianalfoni I have a thought that `appMounted` signal could be root of some problems with debugger:
- It doesn't occured when me reset model from debugger
- it is occured every time we load an app no matter if debugger will try to replay from localStorage or not

**Comment by christianalfoni** [comment]
Think we are okay now? Please create issue or talk at gitter if any more issues with this
